### ISSUE TITLE
Component class name clarification Skype SkypeURIs SkypeURITutorial_AndroidApps.md

### ISSUE THREAD

**Issue by rugemo** [OfficeDev/skype-docs#619]
Could you clarify the component class name. When using the values documented at 

https://docs.microsoft.com/en-us/skype-sdk/skypeuris/skypeuritutorial_androidapps 

Skype fails to open and throws an activity not found exception.

I’ve uploaded a simple app to GitHub to test which component name works.

One button attempts to launch Skype using an intent provided by the package manager.
A second button attempts to launch Skype using `"com.skype.raider", "com.skype.raider.Main"` as detailed in the documentation.

The app catches any ActivityNotFoundException thrown and displays an error.

https://github.com/rugemo/skypelaunchertest

I have Skype version 8.61.0.96 installed.

I ran the  sample app on the follow devices.

Samsung S7 running Android 7
Moto G7 running Android 9
Xiaomi Mi6 running Android 10
Pixel 3a running Android 11 beta 3

Findings…

The component class name now seems to be com.skype4life.MainActivity. Here is the output from adb.

```
adb shell pm dump com.skype.raider | grep -A 1 MAIN
      android.intent.action.MAIN:
        4318134 com.skype.raider/com.skype4life.MainActivity filter 45bd2e5

          Action: "android.intent.action.MAIN"
          Category: "android.intent.category.LAUNCHER"

          Action: "android.intent.action.MAIN"
          Category: "android.intent.category.LAUNCHER"
```

Assuming Skype is installed, the following code grabs the launch intent fro the package manager.

```
val intent = packageManager.getLaunchIntentForPackage("com.skype.raider") ?: Intent()
intent.action = Intent.ACTION_VIEW
intent.data = Uri.parse("skype:" + "live:echo123" + "?chat")
intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
startActivity(intent)
```

If we debug this intent object again the value of the component class name is com.skype4life.MainActivity.

![Screenshot 2020-09-05 at 12 54 34](https://user-images.githubusercontent.com/43332582/92357869-dda6da80-f0e8-11ea-9582-0581f0892be5.png)

Could you clarify the correct component class name? 

If there is a mistake, could the documentation be updated to describe the correct way to launch Skype from a 3rd party app?

Alternatively, If I have missed something please let me know.

Thanks in advance.
